<h1>POKYNY PRO AUTORY</h1>
<h2>Jazyk příspěvků</h2>
<p>Příspěvky musí být v českém nebo anglickém jazyce</p>
<h2>Rozsah příspěvků</h2>
<p>Maximální povolený rozsah je 5 stránek</p>
<h2>Odevzdání příspěvku</h2>
<p>Příspěvek k posouzení je třeba odevzdat ve formátu PDF prostřednictvím formuláře dostupného v systému Webové konference. Pokud dosud nemáte v systému účet, tak se prosím registrujte</p>