<h1>Editace příspěvku</h1><br><br>
<form method="post">
    <div class="form-group">
        <?php foreach ($eprispevek as $prispevek) : ?>
        <label for="nazev">Název příspěvku: ***</label>
        <input type="text" class="form-control" name="nazev" value="<?= $prispevek['nazev'] ?>" /><br /><br>
        <label for="popis">Popis příspěvku: ***</label>
        <textarea type="text" rows="5" class="form-control" name="text"><?= $prispevek['text'] ?></textarea><br /><br>
        <label for="soubor">PDF Soubor:</label>
        <input type="file"  name="soubor" /><br /><br>
        <input type="hidden" name="jmeno_autor" value="<?= $prispevek['jmeno_autor'] ?>" />
        <label for="antispam">Zadejte součet 3 + 4:</label>
        <input type="text" class="form-control"  name="soucet" /><br /><br>
        <?php endforeach ?>
    </div>
    <input type="submit" class="btn btn-default" value="Uprav" />
</form>

<p style="color:red; font-weight: bold">*** Povinný údaj</p>