<?php foreach ($euzivatele as $euzivatel) : ?><h1>Správa uživatele: <?= $euzivatel['jmeno_prijmeni'] ?></h1><br><br>
    <form method="post">
        <div class="form-group">
            <label for="name">Přihlašovací jméno: ***</label>
            <input id="name" type="text" class="form-control" name="jmeno" value="<?= $euzivatel['jmeno'] ?>"/><br />
            <label for="name_surname">Jméno a příjmení: ***</label>
            <input id="name_surname "type="text" class="form-control" name="jmeno_prijmeni" value="<?= $euzivatel['jmeno_prijmeni'] ?>"/><br />
            <label for="email">E-mail:</label>
            <input id="email" type="email" class="form-control" name="email" value="<?= $euzivatel['email'] ?>"/><br />
            <label for="sel1">Typ:</label>
            <select class="form-control" id="sel1" name="typ">
                <option value="U">U</option>
                <option value="R">R</option>
                <option value="A">A</option>
            </select>
        </div><br />
        <input type="submit" class="btn btn-default" value="Vlož" />
    </form>
<?php endforeach ?>
<p style="color:red; font-weight: bold">*** Povinný údaj</p>