<h1>Přihlášení do systému</h1><br><br>
<form method="post">
    <div class="form-group">
        <label for="name">Přihlašovací jméno:</label>
        <input type="text" class="form-control" name="jmeno" /><br />
        <label for="pwd">Heslo:</label>
        <input type="password" class="form-control" name="heslo" /><br />
    </div>
    <input type="submit" class="btn btn-default" value="Přihlásit se" />
</form><br><br>
<h4><a href="registrace">Nový uživatel</a></h4>