<h2>Seznam příspěvků</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                Datum příspěvku
            </th>
            <th>
                Název příspěvku
            </th>
            <th>
                Popis příspěvku
            </th>
            <th>
                Vymaž příspěvek
            </th>
            <th>
                Přihlášený užavatel:
            </th>
            <th>
                Stav příspěvku:
            </th>
            <th>
                Hodnocení:
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($prispevky as $prispevek) : ?>
            <tr>
                <td>
                    <?= $prispevek['datum'] ?>
                </td>
                <td>
                    <a href="eprispevek/<?= $prispevek['id_prispevek'] ?>/<?= $prispevek['id_autor'] ?>"><?= $prispevek['nazev'] ?></a>
                </td>
                <td>
                    <?= $prispevek['text'] ?>
                </td>
                <td>
                    <a href="prispevky/vymazat/<?= $prispevek['id_prispevek'] ?>/<?= $prispevek['id_autor'] ?>"><button type="button" class="btn btn-danger">Vymaž příspěvek</button></a>
                </td>
                <td>
                    <?= $prispevek['jmeno_prijmeni'] ?>
                </td>
                <td>
                    <?= $prispevek['stav'] ?>
                </td>
                <td>
                    <?= $prispevek['hodnoceno'] ?>
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>
<h4><?php foreach ($iduzivatele as $iduzivatel) : ?><a href="prispevek/<?= $iduzivatel['id_uzivatel'] ?>">Nový příspěvek</a><br><br>
    Přihlášený uživatel: <?= $iduzivatel['jmeno_prijmeni'] ?><?php endforeach ?> &nbsp;&nbsp;&nbsp;&nbsp; <a href="prihlaseni/odhlasit">Odhlásit se</a></h4>
