<h1>Nový příspěvek</h1><br><br>
<form method="post">
    <div class="form-group">
        <label for="name">Název příspěvku: ***</label>
        <input type="text" class="form-control" name="nazev" /><br /><br>
        <label for="popis">Popis příspěvku: ***</label>
        <textarea type="text" rows="5" class="form-control" name="text" /></textarea><br /><br>
        <label for="file">PDF Soubor:</label>
        <input id="soubor" type="file" name="soubor" /><br /><br>
        <input type="hidden" name="jmeno_autor" value="<?php foreach ($uzivatele as $uzivatel) : ?><?= $uzivatel['jmeno_prijmeni'] ?><?php endforeach ?>" />
        <label for="antispam">Zadejte součet 3 + 4:</label>
        <input type="text" class="form-control"  name="soucet" /><br /><br>
    </div>
    <input type="submit" class="btn btn-default" value="Vlož" />
</form>

<p style="color:red; font-weight: bold">*** Povinný údaj</p>