<h2>Seznam příspěvků</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                Datum příspěvku
            </th>
            <th>
                Název příspěvku
            </th>
            <th>
                Popis příspěvku
            </th>
            <th>
                Stav příspěvku:
            </th>
            <th>
                Hodnocení:
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($prispevky as $prispevek) : ?>
            <tr>
                <td>
                    <?= $prispevek['datum'] ?>
                </td>
                <td>
                    <a href="eprispevek/<?= $prispevek['id_prispevek'] ?>/<?= $prispevek['id_autor'] ?>"><?= $prispevek['nazev'] ?></a>
                </td>
                <td>
                    <?= $prispevek['text'] ?>
                </td>
                <td>
                    <?= $prispevek['stav'] ?>
                </td>
                <td>
                    <?= $prispevek['hodnoceni'] ?>
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>
<h4>Přihlášený uživatel: <?php foreach ($prispevky as $prispevek) : ?><?= $prispevek['jmeno_autor'] ?><?php endforeach ?> &nbsp;&nbsp;&nbsp;&nbsp; <a href="prihlaseni/odhlasit">Odhlásit se</a></h4>
