<h1>Registrace do systému</h1><br><br>
<form method="post">
    Přihlašovací jméno:<br /><br>
    <input type="text" name="jmeno" /><br /><br>
    Heslo:<br /><br>
    <input type="password" name="heslo" /><br /><br>
    Jméno a příjmení:<br /><br>
    <input type="text" name="jmeno_prijmeni" /><br /><br>
    E-mail:<br /><br>
    <input type="email" name="email" /><br /><br><br>
    <input type="submit" value="Registrovat" />
</form>