<h1>Registrace do systému</h1><br><br>
<form method="post">
    <div class="form-group">
        <label for="name">Přihlašovací jméno: ***</label>
        <input type="text" class="form-control" name="jmeno" /><br />
        <label for="pwd">Heslo: ***</label>
        <input type="password" class="form-control" name="heslo" /><br />
        <label for="pwd">Heslo znovu: ***</label>
        <input type="password" class="form-control" name="heslo_znovu" /><br />
        <label for="name_surname">Jméno a příjmení: ***</label>
        <input type="text" class="form-control" name="jmeno_prijmeni" /><br />
        <label for="email">E-mail: ***</label>
        <input type="email" class="form-control" name="email" /><br />
        <label for="antispam">Zadejte součet 3 + 4:</label>
        <input type="text" class="form-control" name="soucet" /><br />
    </div>
    <input type="submit" class="btn btn-default" value="Registrovat" />
</form>

<p style="color:red; font-weight: bold">*** Povinný údaj</p>