<html>
    <head>
        <meta charset="UTF-8">
        <base href="/localhost:220" />
        <title><?= $titulek ?></title>
        <meta name="description" content="<?= $popis ?>" />
        <meta name="keywords" content="<?= $klicova_slova ?>" />
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <script src="js/jquery.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <style>
            .bg-1 { 
                background-color: #1abc9c;
                color: #ffffff;
            }
            .bg-2 { 
                background-color: #474e5d;
                color: #ffffff;
            }
            .bg-3 { 
                background-color: #ffffff;
                color: #555555;
            }
            .container-fluid {
                padding-top: 70px;
                padding-bottom: 70px;
            }
        </style>
    </head>
    <body>

        <nav class="navbar navbar-default">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>                        
                    </button>
                    <a class="navbar-brand" href="uvod">Domů</a>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="okonferenci">O KONFERENCI</a></li>
                        <li><a href="organizatori">ORGANIZÁTOŘI</a></li>
                        <li><a href="autor">POKYNY PRO AUTORY</a></li>
                    </ul>
                </div>
            </div>
        </nav>


        <div class="container-fluid bg-3 text-center">

            <?php $this->kontroler->vypisPohled(); // vložení aktuálního pohledu do šablony ?>
        </div>
        <footer class="container-fluid bg-2 text-center">
            <p>Webová konference ©2017, Radek Švub</p> 
        </footer>

    </body>
</html>