<h1>Editace stavu příspěvku</h1>
<h3>Název: <span class="bg-info"><?php foreach ($rprispevky as $prispevek) : ?><?= $prispevek['nazev'] ?><?php endforeach ?></span></h3>

<form method="post">
    <div class="form-group">
        <label for="org">STAV PŘÍSPĚVKU: ***</label>
        <select class="form-control" id="sel1" name="stav">
            <option value="1">1 = V recenzním řízení</option>
            <option value="2">2 = Přijat</option>
            <option value="3">3 = Odmítnut</option>
        </select><br />
    </div>
    <input type="submit" class="btn btn-default" value="Vlož" />
</form>

<p style="color:red; font-weight: bold">*** Povinný údaj</p>

<table class="table table-striped">
    <thead>
        <tr>
            <th>
                Datum příspěvku
            </th>
            <th>
                Název příspěvku
            </th>
            <th>
                Autor příspěvku
            </th>
            <th>
                Recenzenti
            </th>
            <th>
                Hodnoceni
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($sprispevky as $sprispevek) : ?>
            <tr>
                <td>
                    <?= $sprispevek['datum'] ?>
                </td>
                <td>
                    <?= $sprispevek['nazev'] ?>
                </td>
                <td>
                    <?= $sprispevek['jmeno_autor'] ?>
                </td>
                <td>
                    <?= $sprispevek['jmeno_recenzent'] ?>
                </td>
                <td>
                    <?= $sprispevek['hodnoceni'] ?>
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>
<h4>Prihlášený uživatel: Administrátor &nbsp;&nbsp;&nbsp;&nbsp; <a href="prihlaseni/odhlasit">Odhlásit se</a></h4>