<h2>Spravovat příspěvky</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                Datum příspěvku
            </th>
            <th>
                Název příspěvku
            </th>
            <th>
                Autor příspěvku
            </th>
            <th>
                Recenzenti
            </th>
            <th>
                Přiřaď recenzenta
            </th>
            <th>
                Rozhodnutí
            </th>
            <th>
                Stav příspěvku
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($sprispevky as $sprispevek) : ?>
            <tr>
                <td>
                    <?= $sprispevek['datum'] ?>
                </td>
                <td>
                    <a href="sprispevek/<?= $sprispevek['id_prispevek'] ?>"><?= $sprispevek['nazev'] ?></a>
                </td>
                <td>
                    <?= $sprispevek['jmeno_autor'] ?>
                </td>
                <td>
                    <?= $sprispevek['jmeno_recenzent'] ?>
                </td>
                <td>
                    <a href="sprispevek/<?= $sprispevek['id_prispevek'] ?>"><button type="button" class="btn btn-info">Přidej recenzenta</button></a>
                </td>
                <td>
                    <a href="sprispevek2/<?= $sprispevek['id_prispevek'] ?>"><button type="button" class="btn btn-danger">Zadej stav příspěvku</button></a>
                </td>
                <td>
                    <?= $sprispevek['stav'] ?>
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>
<h4>Prihlášený uživatel: Administrátor &nbsp;&nbsp;&nbsp;&nbsp; <a href="prihlaseni/odhlasit">Odhlásit se</a></h4>
