<h2>Správa uživatelů</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                Jméno a příjmení
            </th>
            <th>
                E-mail
            </th>
            <th>
                Typ
            </th>
            <th>
                Vymaž uživatele
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($uzivatele as $uzivatel) : ?>
            <tr>
                <td>
                    <a href="euzivatele/<?= $uzivatel['id_uzivatel'] ?>"><?= $uzivatel['jmeno_prijmeni'] ?></a>
                </td>
                <td>
                    <?= $uzivatel['email'] ?>
                </td>
                <td>
                    <?= $uzivatel['typ'] ?>
                </td>
                <td>
                    <a href="uzivatele/vymazat/<?= $uzivatel['id_uzivatel'] ?>"><button type="button" class="btn btn-danger">Vymaž uživatele</button></a>
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>
<h4><a href="sprispevky">Spravovat příspěvky</a><br><br>Přihlášený uživatel: Administrátor - <a href="prihlaseni/odhlasit">Odhlásit se</a></h4>
